"""Add barbearia_id to all tables

Revision ID: d5be5a5a5a5f
Revises: 
Create Date: 2026-05-17 15:51:51.378064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5be5a5a5a5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Aplica restricoes unicas nos campos de login social dos clientes.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['google_id'])
        batch_op.create_unique_constraint(None, ['facebook_id'])

    # ### end Alembic commands ###


def downgrade():
    # Remove as restricoes criadas no upgrade.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
